/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "cashier.payment": [
        {
            "name": "id",
            "required": true
        }
    ],
    "cashier.webhook": [],
    "login": [],
    "register": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "dashboard.index": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.update": [],
    "logout": [],
    "comments.store": [],
    "comments.show": [
        {
            "name": "comment",
            "required": true
        }
    ],
    "comments.destroy": [
        {
            "name": "comment",
            "required": true
        }
    ],
    "comments.getReplies": [
        {
            "name": "comment",
            "required": true
        }
    ],
    "comments.storeReply": [
        {
            "name": "comment",
            "required": true,
            "binding": "id"
        }
    ],
    "workspaces.index": [],
    "workspaces.create": [],
    "workspaces.store": [],
    "workspaces.show": [
        {
            "name": "workspace",
            "required": true,
            "binding": "id"
        }
    ],
    "workspaces.board.create": [
        {
            "name": "workspace",
            "required": true,
            "binding": "id"
        }
    ],
    "workspaces.board.show": [
        {
            "name": "workspace",
            "required": true,
            "binding": "id"
        },
        {
            "name": "board",
            "required": true,
            "binding": "id"
        }
    ],
    "board.tasks.index": [
        {
            "name": "workspace",
            "required": true
        },
        {
            "name": "board",
            "required": true
        }
    ],
    "boards.task.store": [
        {
            "name": "workspace",
            "required": true,
            "binding": "id"
        },
        {
            "name": "board",
            "required": true,
            "binding": "id"
        }
    ],
    "board.tasks.uploadFile": [
        {
            "name": "workspace",
            "required": true,
            "binding": "id"
        },
        {
            "name": "board",
            "required": true,
            "binding": "id"
        },
        {
            "name": "task",
            "required": true,
            "binding": "id"
        }
    ],
    "board.tasks.uploadFiles": [
        {
            "name": "workspace",
            "required": true,
            "binding": "id"
        },
        {
            "name": "board",
            "required": true,
            "binding": "id"
        },
        {
            "name": "task",
            "required": true,
            "binding": "id"
        }
    ],
    "board.tasks.deleteFile": [
        {
            "name": "workspace",
            "required": true,
            "binding": "id"
        },
        {
            "name": "board",
            "required": true,
            "binding": "id"
        },
        {
            "name": "mediaId",
            "required": true
        }
    ],
    "board.tasks.archive": [
        {
            "name": "workspace",
            "required": true,
            "binding": "id"
        },
        {
            "name": "board",
            "required": true,
            "binding": "id"
        },
        {
            "name": "task",
            "required": true,
            "binding": "id"
        }
    ],
    "board.tasks.unarchive": [
        {
            "name": "workspace",
            "required": true,
            "binding": "id"
        },
        {
            "name": "board",
            "required": true,
            "binding": "id"
        },
        {
            "name": "task",
            "required": true,
            "binding": "id"
        }
    ],
    "board.tasks.update": [
        {
            "name": "workspace",
            "required": true,
            "binding": "id"
        },
        {
            "name": "board",
            "required": true,
            "binding": "id"
        },
        {
            "name": "task",
            "required": true
        }
    ],
    "board.update-tasks": [
        {
            "name": "workspace",
            "required": true,
            "binding": "id"
        },
        {
            "name": "board",
            "required": true,
            "binding": "id"
        }
    ],
    "board.task.delete": [
        {
            "name": "workspace",
            "required": true,
            "binding": "id"
        },
        {
            "name": "board",
            "required": true,
            "binding": "id"
        },
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.login": [],
    "admin.dashboard": [],
    "admin.logout": [],
    "admin.users.index": [],
    "admin.users.store": [],
    "admin.users.show": [
        {
            "name": "user",
            "required": true
        }
    ],
    "admin.users.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.users.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.workspaces.index": [],
    "admin.workspaces.create": [],
    "admin.workspaces.store": [],
    "admin.workspaces.show": [
        {
            "name": "workspace",
            "required": true
        }
    ],
    "admin.workspaces.edit": [
        {
            "name": "workspace",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.workspaces.update": [
        {
            "name": "workspace",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.workspaces.destroy": [
        {
            "name": "workspace",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.boards.index": [],
    "admin.boards.store": [],
    "admin.boards.show": [
        {
            "name": "board",
            "required": true
        }
    ],
    "admin.boards.update": [
        {
            "name": "board",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.boards.destroy": [
        {
            "name": "board",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.tasks.index": [],
    "admin.tasks.store": [],
    "admin.tasks.show": [
        {
            "name": "task",
            "required": true
        }
    ],
    "admin.tasks.update": [
        {
            "name": "task",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.tasks.destroy": [
        {
            "name": "task",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.plans.index": [],
    "admin.plans.store": [],
    "admin.plans.show": [
        {
            "name": "plan",
            "required": true
        }
    ],
    "admin.plans.update": [
        {
            "name": "plan",
            "required": true
        }
    ],
    "admin.plans.destroy": [
        {
            "name": "plan",
            "required": true
        }
    ],
    "admin.subscriptions.index": [],
    "admin.subscriptions.store": [],
    "admin.subscriptions.show": [
        {
            "name": "subscription",
            "required": true
        }
    ],
    "admin.subscriptions.update": [
        {
            "name": "subscription",
            "required": true
        }
    ],
    "admin.subscriptions.destroy": [
        {
            "name": "subscription",
            "required": true
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
