/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "login": [],
    "register": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.update": [],
    "logout": [],
    "boards.index": [],
    "boards.task.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "boards.update-tasks": [],
    "boards.task.delete": [
        {
            "name": "id",
            "required": true
        }
    ],
    "tasks.index": [],
    "tasks.store": [],
    "tasks.update": [
        {
            "name": "task",
            "required": true
        }
    ],
    "tasks.uploadFile": [
        {
            "name": "task",
            "required": true
        }
    ],
    "tasks.uploadFiles": [
        {
            "name": "task",
            "required": true
        }
    ],
    "tasks.deleteFile": [
        {
            "name": "mediaId",
            "required": true
        }
    ],
    "tasks.archive": [
        {
            "name": "task",
            "required": true,
            "binding": "id"
        }
    ],
    "tasks.unarchive": [
        {
            "name": "task",
            "required": true,
            "binding": "id"
        }
    ],
    "comments.store": [],
    "comments.show": [
        {
            "name": "comment",
            "required": true
        }
    ],
    "comments.destroy": [
        {
            "name": "comment",
            "required": true
        }
    ],
    "comments.getReplies": [
        {
            "name": "comment",
            "required": true
        }
    ],
    "comments.storeReply": [
        {
            "name": "comment",
            "required": true,
            "binding": "id"
        }
    ],
    "workspaces.index": [],
    "workspaces.create": [],
    "workspaces.store": [],
    "workspaces.show": [
        {
            "name": "workspace",
            "required": true,
            "binding": "id"
        }
    ],
    "workspaces.board.create": [
        {
            "name": "workspace",
            "required": true,
            "binding": "id"
        }
    ],
    "workspaces.board.show": [
        {
            "name": "workspace",
            "required": true,
            "binding": "id"
        },
        {
            "name": "board",
            "required": true,
            "binding": "id"
        }
    ],
    "board.tasks.index": [
        {
            "name": "workspace",
            "required": true
        },
        {
            "name": "board",
            "required": true
        }
    ],
    "boards.task.store": [
        {
            "name": "workspace",
            "required": true,
            "binding": "id"
        },
        {
            "name": "board",
            "required": true,
            "binding": "id"
        }
    ],
    "board.tasks.update": [
        {
            "name": "workspace",
            "required": true
        },
        {
            "name": "board",
            "required": true
        },
        {
            "name": "task",
            "required": true
        }
    ],
    "board.tasks.uploadFile": [
        {
            "name": "workspace",
            "required": true,
            "binding": "id"
        },
        {
            "name": "board",
            "required": true,
            "binding": "id"
        },
        {
            "name": "task",
            "required": true
        }
    ],
    "board.tasks.uploadFiles": [
        {
            "name": "workspace",
            "required": true,
            "binding": "id"
        },
        {
            "name": "board",
            "required": true,
            "binding": "id"
        },
        {
            "name": "task",
            "required": true
        }
    ],
    "board.tasks.deleteFile": [
        {
            "name": "workspace",
            "required": true,
            "binding": "id"
        },
        {
            "name": "board",
            "required": true,
            "binding": "id"
        },
        {
            "name": "mediaId",
            "required": true
        }
    ],
    "board.tasks.archive": [
        {
            "name": "workspace",
            "required": true,
            "binding": "id"
        },
        {
            "name": "board",
            "required": true,
            "binding": "id"
        },
        {
            "name": "task",
            "required": true,
            "binding": "id"
        }
    ],
    "board.tasks.unarchive": [
        {
            "name": "workspace",
            "required": true,
            "binding": "id"
        },
        {
            "name": "board",
            "required": true,
            "binding": "id"
        },
        {
            "name": "task",
            "required": true,
            "binding": "id"
        }
    ],
    "board.task.update": [
        {
            "name": "workspace",
            "required": true,
            "binding": "id"
        },
        {
            "name": "board",
            "required": true,
            "binding": "id"
        },
        {
            "name": "id",
            "required": true
        }
    ],
    "board.update-tasks": [
        {
            "name": "workspace",
            "required": true,
            "binding": "id"
        },
        {
            "name": "board",
            "required": true,
            "binding": "id"
        }
    ],
    "board.task.delete": [
        {
            "name": "workspace",
            "required": true,
            "binding": "id"
        },
        {
            "name": "board",
            "required": true,
            "binding": "id"
        },
        {
            "name": "id",
            "required": true
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
